# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-01 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Variables',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('key', models.CharField(db_index=True, max_length=255)),
                ('value', models.TextField()),
                ('created_when', models.DateTimeField(auto_now_add=True)),
                ('modified_when', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
