# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-11 03:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seastar', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variables',
            options={'verbose_name_plural': 'variables'},
        ),
        migrations.AlterField(
            model_name='variables',
            name='key',
            field=models.CharField(db_index=True, help_text='key by which text will be displayed on UI', max_length=255),
        ),
        migrations.AlterField(
            model_name='variables',
            name='value',
            field=models.TextField(help_text='Text that will be displayed on UI'),
        ),
    ]
